name: mapsconda  # overridden at install, so this is for your use with conda env
dependencies:
	- python=3.6
	- pip:
		- flask
		- pandas
		- numpy
		- bokeh
		- GDAL
		- fiona
		- rtree
		- shapely
		- geopandas
		- gunicorn